In [4]:
import cv2
from keras.models import load_model
import numpy as np

model = load_model('keras_model.h5')

cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True:
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation=cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) /
                        127.0) - 1  # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)

    if prediction[0][0] >= 0.5:
        print("Rock")
    elif prediction[0][1] >= 0.5:
        print("Paper")
    elif prediction[0][2] >= 0.5:
        print("Scissor")
    else:
        print("Nothing")

    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

[[3.2300458e-16 7.7707307e-10 1.0000000e+00 7.4742967e-09]]
[[3.1608614e-15 2.3475266e-09 1.0000000e+00 4.7867921e-08]]
[[6.2817545e-17 7.6258582e-09 1.0000000e+00 2.2612326e-08]]
[[2.6313231e-14 2.7021386e-05 9.9996650e-01 6.3848397e-06]]
[[1.1812656e-10 9.1861111e-01 7.6204933e-02 5.1840041e-03]]
[[5.2345167e-10 9.1861695e-01 5.9377598e-03 7.5445279e-02]]
[[1.0341084e-10 9.6565729e-01 3.3207515e-03 3.1022003e-02]]
[[8.9164265e-10 8.9267963e-01 3.5527926e-02 7.1792386e-02]]
[[9.4618724e-10 8.8848507e-01 1.0344104e-02 1.0117071e-01]]
[[2.8556311e-09 9.7935176e-01 7.3383497e-03 1.3309913e-02]]
[[7.3325452e-09 9.5394510e-01 2.3619616e-02 2.2435345e-02]]
[[1.7081723e-09 9.8425376e-01 6.1617140e-03 9.5845535e-03]]
[[1.1254402e-09 6.9271573e-03 8.5091728e-01 1.4215553e-01]]
[[8.3883533e-10 5.3602569e-03 9.9340445e-01 1.2352834e-03]]
[[2.5848252e-09 4.2956587e-02 8.7966967e-01 7.7373803e-02]]
[[3.3608267e-09 1.7317373e-02 8.8264751e-01 1.0003509e-01]]
[[7.4284854e-09 2.2946645e-01 7.5508964e