In [7]:
import cv2
from keras.models import load_model
import numpy as np

model = load_model('keras_model.h5')

cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True:
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation=cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) /
                        127.0) - 1  # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)

    pred = [prediction[0][0],prediction[0][1],prediction[0][2],prediction[0][3]]

    max_pred = pred.index(max(pred))

    if max_pred == 0:
        print("Rock")
    elif max_pred == 1:
        print("Paper")
    elif max_pred == 2:
        print("Scissor")
    else:
        print("Nothing")

    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

Nothing
[[0.03077151 0.08796749 0.01934255 0.8619185 ]]
Nothing
[[0.01547502 0.03159657 0.01492195 0.9380065 ]]
Nothing
[[0.19293234 0.100887   0.06093765 0.645243  ]]
Nothing
[[0.12356771 0.03703063 0.01898223 0.82041943]]
Nothing
[[0.06051272 0.07428394 0.02343891 0.8417644 ]]
Nothing
[[0.06520759 0.05103843 0.07253848 0.81121546]]
Nothing
[[0.07120097 0.12364022 0.10872077 0.696438  ]]
Nothing
[[0.11199941 0.20739041 0.08064608 0.59996414]]
Nothing
[[0.03364013 0.11189535 0.04044858 0.8140159 ]]
Paper
[[0.13260771 0.47932568 0.0769686  0.311098  ]]
Nothing
[[0.0808747  0.23877771 0.04308271 0.63726485]]
Nothing
[[0.07545629 0.3790548  0.02698104 0.51850784]]
Nothing
[[0.0815995  0.11005697 0.16727248 0.6410711 ]]
Nothing
[[0.16709042 0.3374236  0.10922429 0.38626164]]
Nothing
[[0.01015593 0.04673497 0.01723226 0.92587686]]
Nothing
[[0.1337313  0.35667723 0.08255279 0.42703864]]
Paper
[[0.14347196 0.4047468  0.05642358 0.3953577 ]]
Paper
[[0.21784568 0.4078933  0.05992524 0.31433582]

In [6]:
a = [4, 6, 3]

print(a.index(max(a)))

1
