In [2]:
import cv2
from keras.models import load_model
import numpy as np

model = load_model('keras_model.h5')

cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True:
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation=cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) /
                        127.0) - 1  # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)

    pred = [prediction[0][0],prediction[0][1],prediction[0][2],prediction[0][3]]

    max_pred = pred.index(max(pred))

    if max_pred == 0:
        print("Rock")
    elif max_pred == 1:
        print("Paper")
    elif max_pred == 2:
        print("Scissor")
    else:
        print("Nothing")

    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

Nothing
[[0.0746472  0.07176513 0.0372529  0.8163348 ]]
Nothing
[[0.14681475 0.16418834 0.14983863 0.5391582 ]]
Nothing
[[0.03086763 0.09996545 0.01498119 0.85418576]]
Paper
[[0.16952157 0.5084     0.1073346  0.21474388]]
Nothing
[[0.11057802 0.02777399 0.04766926 0.8139787 ]]
Nothing
[[0.05979589 0.05927953 0.05060744 0.83031714]]
Nothing
[[0.02843821 0.06076232 0.10276569 0.8080338 ]]
Nothing
[[0.10743681 0.07603268 0.16734271 0.64918774]]
Nothing
[[0.03704447 0.11131217 0.079962   0.77168137]]
Nothing
[[0.03363302 0.04236488 0.12493184 0.7990703 ]]
Nothing
[[0.0562703  0.13092193 0.2524562  0.56035155]]
Nothing
[[0.06914528 0.06292938 0.17128454 0.6966408 ]]
Scissor
[[0.08747858 0.05395797 0.56826496 0.2902985 ]]
Scissor
[[0.08722173 0.05081328 0.82150793 0.04045706]]
Nothing
[[0.03465442 0.05222916 0.2448944  0.668222  ]]
Nothing
[[0.06501053 0.1140381  0.13861088 0.6823405 ]]
Nothing
[[0.12014854 0.3344245  0.384083   0.16134396]]
Scissor
[[0.09263189 0.10176259 0.662333   0.14327

In [6]:
a = [4, 6, 3]

print(a.index(max(a)))

1
